In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

In [3]:
base_dir=Path.cwd().parent
data = base_dir / "data" / "bbc_news_dataset.csv"

In [4]:
df = pd.read_csv(data)

In [5]:
df.head()

   ArticleId                                               Text  Category
0       1833  worldcom ex-boss launches defence lawyers defe...  business
1        154  german business confidence slides german busin...  business
2       1101  bbc poll indicates economic gloom citizens in ...  business
3       1976  lifestyle  governs mobile choice  faster  bett...      tech
4        917  enron bosses in $168m payout eighteen former e...  business

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ArticleId  1490 non-null   int64
 1   Text       1490 non-null   str
 2   Category   1490 non-null   str
dtypes: int64(1), str(2)
memory usage: 35.1 KB

In [10]:
df[df["ArticleId"]<10]

      ArticleId                                               Text  Category
233           2  worldcom boss  left books alone  former worldc...  business
922           4  yeading face newcastle in fa cup premiership s...     sport
1423          7  blair prepares to name poll date tony blair is...  politics

In [12]:
X = df['Text']
Y = df['Category']

In [13]:
category_names = df['Category'].unique()
print(category_names)

<StringArray>
['business', 'tech', 'politics', 'sport', 'entertainment']
Length: 5, dtype: str